import Foundation

extension LingShuEngineeringArtifactService {
    func makeCrawlerArtifacts(root: URL, stamp: String, prompt: String, reply: String) -> [LingShuMaterializedArtifact] {
        let directory = root.appendingPathComponent("software-crawler-\(stamp)", isDirectory: true)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        let crawlerURL = directory.appendingPathComponent("crawler.py")
        let readmeURL = directory.appendingPathComponent("README.md")
        let sampleHTMLURL = directory.appendingPathComponent("sample.html")
        let sampleResultURL = directory.appendingPathComponent("sample_result.json")

        var artifacts: [LingShuMaterializedArtifact] = []
        if write(crawlerSource, to: crawlerURL) {
            try? FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: crawlerURL.path)
            artifacts.append(.init(title: "Web 爬虫可运行代码", location: crawlerURL.path, producer: "执行"))
        }

        if write(crawlerReadme(prompt: prompt, reply: reply), to: readmeURL) {
            artifacts.append(.init(title: "爬虫运行说明", location: readmeURL.path, producer: "执行"))
        }

        if write(sampleHTML, to: sampleHTMLURL) {
            artifacts.append(.init(title: "爬虫本地测试页", location: sampleHTMLURL.path, producer: "验证"))
        }

        if write(sampleResult, to: sampleResultURL) {
            artifacts.append(.init(title: "爬虫样例结果", location: sampleResultURL.path, producer: "验证"))
        }

        return artifacts
    }

    private func crawlerReadme(prompt: String, reply: String) -> String {
        """
        # Web Crawler Artifact

        ## Task
        \(prompt)

        ## Run
        ```bash
        python3 crawler.py https://example.com --limit 10 --output result.json
        ```

        ## Notes
        - Uses only Python standard library.
        - Supports HTTP/HTTPS and local `file://` URLs for validation.
        - Extracts title, links and text preview.

        ## LingShu Summary
        \(reply.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? "LingShu generated a runnable crawler artifact." : reply)
        """
    }

    private var crawlerSource: String {
        """
        #!/usr/bin/env python3
        import argparse
        import json
        import time
        from html.parser import HTMLParser
        from urllib.parse import urljoin
        from urllib.request import Request, urlopen


        class PageParser(HTMLParser):
            def __init__(self, base_url):
                super().__init__()
                self.base_url = base_url
                self.title = ""
                self.links = []
                self._in_title = False
                self._text = []

            def handle_starttag(self, tag, attrs):
                attrs = dict(attrs)
                if tag == "title":
                    self._in_title = True
                if tag == "a" and attrs.get("href"):
                    self.links.append(urljoin(self.base_url, attrs["href"]))

            def handle_endtag(self, tag):
                if tag == "title":
                    self._in_title = False

            def handle_data(self, data):
                cleaned = " ".join(data.split())
                if not cleaned:
                    return
                if self._in_title:
                    self.title += cleaned
                self._text.append(cleaned)

            @property
            def preview(self):
                return " ".join(self._text)[:500]


        def fetch(url, timeout):
            request = Request(url, headers={"User-Agent": "LingShuCrawler/1.0"})
            with urlopen(request, timeout=timeout) as response:
                encoding = response.headers.get_content_charset() or "utf-8"
                return response.read().decode(encoding, errors="replace")


        def crawl(url, limit, timeout):
            html = fetch(url, timeout)
            parser = PageParser(url)
            parser.feed(html)
            return {
                "url": url,
                "title": parser.title.strip(),
                "links": parser.links[:limit],
                "link_count": len(parser.links),
                "preview": parser.preview,
                "fetched_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            }


        def main():
            cli = argparse.ArgumentParser(description="A small runnable web crawler generated by LingShu.")
            cli.add_argument("url", help="Target URL, for example https://example.com or file:///tmp/sample.html")
            cli.add_argument("--limit", type=int, default=10, help="Maximum links in output")
            cli.add_argument("--timeout", type=float, default=12.0, help="Network timeout in seconds")
            cli.add_argument("--output", default="", help="Optional JSON output path")
            args = cli.parse_args()

            result = crawl(args.url, args.limit, args.timeout)
            payload = json.dumps(result, ensure_ascii=False, indent=2)
            if args.output:
                with open(args.output, "w", encoding="utf-8") as file:
                    file.write(payload + "\\n")
            print(payload)


        if __name__ == "__main__":
            main()
        """
    }

    private var sampleHTML: String {
        """
        <!doctype html>
        <html lang="zh-CN">
        <head><meta charset="utf-8"><title>LingShu crawler sample</title></head>
        <body>
          <h1>LingShu crawler sample</h1>
          <a href="/docs">Documentation</a>
          <a href="https://example.com/demo">Demo</a>
          <p>This page is a local validation fixture.</p>
        </body>
        </html>
        """
    }

    private var sampleResult: String {
        """
        {
          "url": "file://sample.html",
          "title": "LingShu crawler sample",
          "links": [
            "file:///docs",
            "https://example.com/demo"
          ],
          "link_count": 2,
          "preview": "LingShu crawler sample Documentation Demo This page is a local validation fixture."
        }
        """
    }
}
